# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from controllers.countdown import CountDown
from functools import partial

class Ui_MainWindow(object):
    count_worker = None

    def startCount(self):
        if self.count_worker != None:
            self.count_worker.stop = True

            return

        timeData = {
            'hours': int(self.hours.text()),
            'minutes': int(self.minutes.text()),
            'seconds': int(self.seconds.text())
        }

        self.hours.setEnabled(False)
        self.minutes.setEnabled(False)
        self.seconds.setEnabled(False)

        self.buttonControll.setText('PARAR')

        self.count_worker = CountDown(timeData)
        self.count_worker.ended.connect(self.counterFinished)
        self.count_worker.emitData.connect(self.setCounterTime)
        self.count_worker.start()
        self.count_worker.exec_()

    def counterFinished(self):
        self.count_worker = None

        self.hours.setEnabled(True)
        self.minutes.setEnabled(True)
        self.seconds.setEnabled(True)

        self.buttonControll.setText('INICIAR')

    def setCounterTime(self, data):
        timeData = {}

        for i in data:
            timeData[i] = str(data[i])

            if len(timeData[i]) == 1:
                timeData[i] = '0' + timeData[i]

        self.hours.setText(timeData['hours'])
        self.minutes.setText(timeData['minutes'])
        self.seconds.setText(timeData['seconds'])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: \'#FFFFFF\'")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hours = QtWidgets.QLineEdit(self.centralwidget)
        self.hours.setGeometry(QtCore.QRect(140, 220, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.hours.setFont(font)
        self.hours.setText("")
        self.hours.setAlignment(QtCore.Qt.AlignCenter)
        self.hours.setObjectName("hours")
        self.minutes = QtWidgets.QLineEdit(self.centralwidget)
        self.minutes.setGeometry(QtCore.QRect(320, 220, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.minutes.setFont(font)
        self.minutes.setText("")
        self.minutes.setAlignment(QtCore.Qt.AlignCenter)
        self.minutes.setObjectName("minutes")
        self.seconds = QtWidgets.QLineEdit(self.centralwidget)
        self.seconds.setGeometry(QtCore.QRect(500, 220, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.seconds.setFont(font)
        self.seconds.setText("")
        self.seconds.setAlignment(QtCore.Qt.AlignCenter)
        self.seconds.setObjectName("seconds")
        self.buttonControll = QtWidgets.QPushButton(self.centralwidget)
        self.buttonControll.setGeometry(QtCore.QRect(330, 380, 111, 51))
        self.buttonControll.setStyleSheet("background-color: rgb(127, 127, 127);")
        self.buttonControll.setObjectName("buttonControll")
        MainWindow.setCentralWidget(self.centralwidget)


        self.buttonControll.clicked.connect(partial(self.startCount))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonControll.setText(_translate("MainWindow", "INICIAR"))

